Update UI when dragging a folder
gkjohnson/urdf-loaders pull request #228
Opened 2022-04-11 09:18 UTC by nikhilweee

Hello!

First of all, thank you for such an amazing tool. This has been a life saver for me. I loved the functionality to drag and drop folders directly in the browser, and this makes it a truly portable solution without me having to install anything.

This all worked fine, however, I noticed that when my folder had multiple URDF files, I was confused as to which one was being loaded. In such cases, I would love the choice to select a model of my choice, and that's exactly what is being addressed in this PR. I'm open to any changes you might suggest.

Thanks,
Nikhil

2022-04-11 16:44 UTC, gkjohnson requested changes
Great! Thanks for the contribution! This is a great addition. A few more requests beyond the comments:

- Can we revert or remove the bundled script files from the PR? They are now automatically generated via CI. I'd actually prefer if you just delete them entirely since they're no longer needed in the master branch.
- Can we enable a scroll bar on the models list to show at most 4 or so model names? Right now you can drag a folder with dozens of files and it scrolls off the page:

![image](https://user-images.githubusercontent.com/734200/162789632-e6e3e1aa-4b40-4b81-9c29-cb85dc57ecc5.png)

2022-04-11 16:44 UTC, gkjohnson commented on javascript/example/src/dragAndDrop.js
> +                while( urdfOptions.firstChild ){
nit: can we remove the spaces in the parens so it matches the rest of the code.

2022-04-13 03:06 UTC, nikhilweee commented on README.md
> +[Demo Here!](https://nikhilweee.me/urdf-loaders/javascript/example/bundle)
Oh yes sorry didn't realise the changes would reflect here too.

2022-04-13 06:45 UTC, nikhilweee commented
@gkjohnson Let me know if this works!

2022-04-14 07:55 UTC, gkjohnson commented
Excellent, thank you!

2022-04-14 07:55 UTC, merged